stages:
    - build_dev
    - build

builddev-job:
  stage: build_dev

  tags:
    - ulb-omp-dev

  script:
    - echo "Install OMP DEVELOP"
    - ./build.sh omp omp
    - ./start-omp dev



build-job:
  stage: build

  needs: 
    - builddev-job

  tags:
    - ulb-omp

  script:
    - echo "Install OMP PRODUCTION"
    - ./build.sh  omp omp
    - ./start-omp prod

