stages:
    - build_dev
    - build


variables:
    GIT_SUBMODULE_STRATEGY: recursive


builddev-job:
  stage: build_dev

  tags:
    - ulb-omp-dev

  script:
    - echo "Install OMP DEVELOP"
    - ./build.sh
    - ./stop-omp dev
    - ./start-omp dev

build-job:
  stage: build

  needs: 
    - builddev-job

  tags:
    - ulb-omp

  script:
    - echo "Install OMP PRODUCTION"
    - ./stop-omp prod
    - ./start-omp prod

