FROM php:7.3-apache

LABEL maintainer="Deutsches Archäologisches Institut: dev@dainst.org"
LABEL author="Deutsches Archäologisches Institut: dev@dainst.org"
LABEL version="1.0"
LABEL description="DAI specific OMP3 Docker container with DAI specific plugins"
LABEL license="GNU GPL 3"

ENV DEBIAN_FRONTEND noninteractive

ARG MYSQL_USER
ARG MYSQL_PASSWORD
ARG MYSQL_DB

### Install packes needed for installing from custom repos ###
RUN apt-get update && apt-get install -y \
    gnupg2 \
    software-properties-common \
    dirmngr \
    wget \
    apt-transport-https

### install packages ###
RUN apt-get update && apt-get install -y \
    bash-completion \
    ca-certificates \
    curl \
    openssl \
    mariadb-server \
    acl \
    build-essential \
    cron \
    expect \
    git \
    libssl-dev \
    nano \
    supervisor \
    unzip \
    expect \
    libbz2-dev \
    libcurl3-dev \
    libicu-dev \
    libedit-dev \
    libxml2-dev \
    zlib1g-dev \
    libzip-dev

RUN docker-php-ext-install \
    bcmath \
    bz2 \
    curl \
    dba \
    intl \
    json \
    mbstring \
    mysqli \
    pdo \
    pdo_mysql \
    readline \
    xml \
    zip

RUN docker-php-ext-enable mysqli

WORKDIR /tmp

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - \
    && apt-get -y install \
    nodejs
RUN curl -sS https://getcomposer.org/installer -o composer-setup.php \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer


### Initialize MySQl database ###
RUN service mysql start && \
    echo "CREATE USER '${MYSQL_USER}'@'localhost' IDENTIFIED BY '${MYSQL_PASSWORD}';" | mysql -u root && \
    echo "UPDATE mysql.user SET plugin = 'mysql_native_password' WHERE User='${MYSQL_USER}'; FLUSH PRIVILEGES;" | mysql -u root && \
    echo "CREATE DATABASE ${MYSQL_DB};" | mysql -u root && \
    echo "GRANT ALL PRIVILEGES on ${MYSQL_DB}.* TO '${MYSQL_USER}'@'localhost'; FLUSH PRIVILEGES;" | mysql -u root

### Install OMP ###
RUN mkdir -p /var/www/files
COPY omp /var/www/html

WORKDIR /var/www/html

# php modules
RUN composer install -v -d lib/pkp --no-dev
RUN composer install -v -d plugins/paymethod/paypal --no-dev

# js modules
RUN npm install -y
RUN npm run build

# config file
RUN cp config.TEMPLATE.inc.php config.inc.php


RUN sed -i 's/allowProtocolRelative = false/allowProtocolRelative = true/' /var/www/html/lib/pkp/classes/core/PKPRequest.inc.php

# initial file rights
WORKDIR /var
RUN chgrp -f -R www-data www && \
    chmod -R 771 www && \
    chmod g+s www && \
    setfacl -Rm o::x,d:o::x www && \
    setfacl -Rm g::rwx,d:g::rwx www

# set file rights (after configuration and installation!)
WORKDIR /var/www
RUN chgrp -f -R www-data html/plugins && \
    chmod -R 771 html/plugins && \
    chmod g+s html/plugins && \
    setfacl -Rm o::x,d:o::x html/plugins && \
    setfacl -Rm g::rwx,d:g::rwx html/plugins

RUN chgrp -f -R www-data html/cache && \
    chmod -R 771 html/cache && \
    chmod g+s html/cache && \
    setfacl -Rm o::x,d:o::x html/cache && \
    setfacl -Rm g::rwx,d:g::rwx html/cache

RUN chgrp -f -R www-data html/public && \
    chmod -R 771 html/public && \
    chmod g+s html/public && \
    setfacl -Rm o::x,d:o::x html/public && \
    setfacl -Rm g::rwx,d:g::rwx html/public

RUN chgrp -f -R www-data files && \
    chmod -R 771 files && \
    chmod g+s files && \
    setfacl -Rm o::x,d:o::x files && \
    setfacl -Rm g::rwx,d:g::rwx files

RUN a2enmod rewrite

### go ###
COPY ./docker-entrypoint-install.sh /usr/local/bin/
ENTRYPOINT ["docker-entrypoint-install.sh"]

EXPOSE 80
