# File: docker-compose.yml
# Access via "https://omp.bibliothek.uni-halle.de"
#
# Call example:
# $ docker-compose -f docker-compose-ompdev-ulb.yml up

version: "3.6"

networks:
  inside:
    external: false

services:
  db:
    image: mariadb:10.2
    # see https://hub.docker.com/_/mariadb
    env_file:
      - .env
    container_name: "ompdev_db_ulb"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - /data/ompdev/db:/var/lib/mysql
      - /data/ompdev/logs/db:/var/log/mysql
      - ./resources/my.cnf:/etc/mysql/conf.d/charset.cnf
    networks:
      - inside
    restart: always

  ompdev:
    image: omp-ulb:${OMP_VERSION_ULB_DEV}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USE_VERSION: "${OMP_VERSION_ULB_DEV}"
    env_file:
      - .env
    container_name: "ompdev_app_ulb"
    hostname: "${COMPOSE_PROJECT_NAME}"
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - /data/ompdev/private/files:/var/www/files
      - /data/ompdev/public:/var/www/html/public
      - /data/ompdev/logs/app:/var/log/apache2
      - /data/ompdev/config/omp.config.inc.php:/var/www/html/config.inc.php
      - /data/ompdev/config/php.ulb.ini:/etc/php7/conf.d/php.ulb.ini:ro
      - /data/ompdev/config/ompdev.conf:/etc/apache2/conf.d/omp.conf
      - /data/ompdev/config/ssl/omp.pem:/etc/ssl/apache2/server.pem:ro
      - /data/ompdev/config/ssl/omp.key:/etc/ssl/apache2/server.key:ro
      - /data/ompdev/config/locale/de_DE:/var/www/html/locale/de_DE
      # ULB custom made plugins
      - /data/ompdev/plugins/ulb-theme:/var/www/html/plugins/themes/ulb-theme
      - /data/ompdev/plugins/searchMarkPlugin:/var/www/html/plugins/generic/searchMarkPlugin
      - /data/ompdev/plugins/setRemoteUrlPlugin:/var/www/html/plugins/generic/setRemoteUrlPlugin
      - /data/ompdev/config/favicon.ico:/var/www/html/favicon.ico

    networks:
      - inside
    depends_on:
      - db
    restart: always
