version: '3.7'

x-env: &env
  MYSQL_USER: omp
  MYSQL_PASSWORD: omp
  MYSQL_DB: omp

services:
  omp_dev:
    container_name: omp_dev
    build:
      context: .
      args:
        <<: *env
    image: dainst/cilantro-omp3
    environment:
      <<: *env
    volumes:
    - ./omp:/var/www/html
    - ./omp_repository:/var/www/files
    ports:
      - "4444:80"
      - "4443:3306"
    networks:
      - omp_dev_network

networks:
  omp_dev_network:
    name: omp_dev_network
