# File: docker-compose.yml
# Access via "https://omp.bibliothek.uni-halle.de"
#
# Call example:
# $ docker-compose -f docker-compose-ompprod-ulb.yml up

version: "3.6"

networks:
  inside:
    external: false
  omp:  
    external: true 

services:
  db:
    image: mariadb:10.2
    # see https://hub.docker.com/_/mariadb
    env_file:
      - .env
    container_name: "ompprod_db_ulb"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - /data/ompprod/db:/var/lib/mysql
      - /data/ompprod/logs/db:/var/log/mysql
      - ./resources/my.cnf:/etc/mysql/conf.d/charset.cnf
#      - ./volumes/migration:/docker-entrypoint-initdb.d
    networks:
      - inside
    restart: always

  ompprod:
    image: omp-ulb:${OMP_VERSION_ULB_PROD}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USE_VERSION: "${OMP_VERSION_ULB_PROD}"
    env_file:
      - .env
    container_name: "ompprod_app_ulb"
    hostname: "${COMPOSE_PROJECT_NAME}"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime
      - /data/ompprod/files:/var/www/files
      - /data/ompprod/public:/var/www/html/public
      - /data/ompprod/logs/app:/var/log/apache2
      - /data/ompprod/config/omp.config.inc.php:/var/www/html/config.inc.php
      - /data/ompprod/config/ompprod.conf:/etc/apache2/conf.d/omp.conf
      - /data/ompprod/config/ssl/omp.pem:/etc/ssl/apache2/server.pem:ro
      - /data/ompprod/config/ssl/omp.key:/etc/ssl/apache2/server.key:ro
      - /data/ompprod/config/locale/de_DE/manager.po:/var/www/html/locale/de_DE/manager.po
      - /data/ompprod/config/locale/de_DE/locale.po:/var/www/html/locale/de_DE/locale.po
      - /data/ompprod/config/locale/de_DE/default.po:/var/www/html/locale/de_DE/default.po
#      - ./volumes/config/apache.htaccess:/var/www/html/.htaccess
#      - ./volumes/php.custom.ini:/usr/local/etc/php/conf.d/custom.ini

    networks:
      - inside
      - omp      
    depends_on:
      - db
    restart: always
