# File: docker-compose.yml
# Access via "http://localhost:8080"
#
# Call example:
# $ docker-compose -f docker-compose-ulb.yml up

version: "3.6"



networks:
  inside:
    external: false

services:
  db:
    image: mariadb:10.2
    # see https://hub.docker.com/_/mariadb
    env_file:
      - .env
    container_name: "omp_db_ulb"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - /home/omp/volumes/db:/var/lib/mysql
      - /home/omp/volumes/logs/db:/var/log/mysql
#      - ./volumes/config/db.charset.conf:/etc/mysql/conf.d/charset.cnf
#      - ./volumes/migration:/docker-entrypoint-initdb.d
    networks:
      - inside
    restart: always

  omp:
    image: omp-ulb
    env_file:
      - .env
    container_name: "omp_app_ulb"
    hostname: "${COMPOSE_PROJECT_NAME}"
    restart: always
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/omp/volumes/files:/var/www/files
      - /home/omp/volumes/public:/var/www/html/public
      - /home/omp/volumes/logs/app:/var/log/apache2
      - /home/omp/volumes/config/omp.config.inc.php:/var/www/html/config.inc.php
      - /home/omp/volumes/config/ssl/omp.pem:/etc/ssl/apache2/server.pem
      - /home/omp/volumes/config/ssl/omp.key:/etc/ssl/apache2/server.key
      - /home/omp/volumes/config/locale/de_DE/manager.po:/var/www/html/locale/de_DE/manager.po


#      - ./volumes/config/apache.htaccess:/var/www/html/.htaccess
#      - ./volumes/php.custom.ini:/usr/local/etc/php/conf.d/custom.ini

    networks:
      - inside
    depends_on:
      - db
    restart: always
