#!/bin/bash

compose_network=omp


docker network inspect $compose_network >/dev/null 2>&1 || \
    docker network create $compose_network

if  [ -z "$1" ] || ([ $1 != "dev" ] && [ $1 != "prod" ] && [ $1 != "local" ])
    then
        echo "Parameter 'dev' or 'prod' or 'local' missing"
        exit 0

elif [ $1 == "dev" ] || [ "$1" == "local" ]
    then
        if [ "$1" == "local" ]; then
            source .env
            cp -v ./resources/omplocal.conf ${PROJECT_DATA_ROOT_DEV}/config/
        fi       
        echo start docker-compose $1
        docker-compose -f docker-compose-omp$1.yml -p $1 up -d

elif [ $1 == "prod" ]
    then
        echo start docker-compose production
        docker-compose -f docker-compose-ompprod.yml -p $1 up -d
fi
