#!/bin/bash

if  [ -z "$1" ] || ([ $1 != "dev" ] && [ $1 != "prod" ])
    then
        echo "Parameter 'dev' oder 'prod' missing"
        exit 0

elif [ $1 == "dev" ]
    then
        echo start docker-compose dev
        docker-compose -f docker-compose-ompdev.yml -p $1 up -d

elif [ $1 == "prod" ]
    then
        echo start docker-compose production
        docker-compose -f docker-compose-ompprod.yml -p $1 up -d
fi
