#!/bin/bash

set -e 

if  [ -z "$1" ] || ([ $1 != "dev" ] && [ $1 != "prod" ] && [ $1 != "local" ])
    then
        echo "parameter 'dev', 'prod' or 'local' is missing"
        exit 0

elif [ "$1" == "dev" ] ||  [ "$1" == "local" ]
    then
        echo "stop docker-compose $1"
        docker-compose -f docker-compose-omp$1.yml -p $1 down

elif [ $1 == "prod" ]
    then
        echo "stop docker compose $1"
        docker-compose -f docker-compose-ompprod.yml -p $1 down
fi

